// Jest 测试环境配置
process.env.NODE_ENV = 'test';
process.env.DATABASE_URL = 'mysql://root:password@localhost:3306/accounting_test';
process.env.JWT_SECRET = 'test-access-secret-at-least-32-chars!!';
process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-at-least-32-chars!!';
process.env.JWT_ACCESS_EXPIRES_IN = '15m';
process.env.JWT_REFRESH_EXPIRES_IN = '7d';
process.env.WECHAT_APPID = 'test-appid';
process.env.WECHAT_SECRET = 'test-secret';
process.env.PORT = '0';
